Repository 51bootcamp-2020/tinysocial, pull requests merged in 2020-01, with the labels that each got.

#8 Update schema and divide resolvers and Implement signUp/SignInWithGoogle resolvers
  .gitignore
  server/fakedb/Event.csv
  server/fakedb/EventParticipant.csv
  server/fakedb/Schedule.csv
  server/fakedb/Tag.csv
  server/fakedb/User.csv
  server/package-lock.json
  server/package.json
  server/src/auth/auth-facebook.js
  server/src/auth/auth-google.js
  server/src/data_importer.js
  server/src/database.js
  server/src/index.js
  server/src/resolvers.js
  server/src/resolvers/event.js
  server/src/resolvers/mutation.js
  server/src/resolvers/query.js
  server/src/resolvers/user.js
  server/src/schema.js
  server/src/utils.js
  web/package-lock.json
  web/package.json
  web/public/index.html
  web/src/App.js
  web/src/index.js
Labels: enhancement, p0

#21 Update DB schema according to new design p0
  server/src/database.js
  server/src/schema.js
Labels: p0

#17 Create sign up feature
  .gitignore
  package-lock.json
  package.json
  server/src/error-messages.js
  server/src/resolvers/mutation.js
  web/package.json
  web/src/App.js
  web/src/components/login-form.js
  web/src/components/signup-form.js
  web/src/index.js
  web/src/pages/landing.js
  web/src/pages/signup.js
Labels: enhancement, p0

#34 Update GraphQL schema
  server/src/database.js
  server/src/schema.js
Labels: p0

#42 Delete duplicate ApolloProvider & Add cookie
  web/package-lock.json
  web/package.json
  web/src/App.js
  web/src/index.js
Labels: bug

#39 Create userpage components
  web/src/components/userpage/event-review-card-list.js
  web/src/components/userpage/event-review-card.js
  web/src/components/userpage/event-review.js
  web/src/components/userpage/event-schedule.js
  web/src/components/userpage/review-write-button.js
  web/src/components/userpage/review-write.js
  web/src/components/userpage/sample-data.js
  web/src/components/userpage/userpage-tabs.js
  web/src/components/utils.js
  web/src/pages/userpage.js
Labels: enhancement

#54 feat: login check & user avatar for userpage
  web/src/App.js
  web/src/components/navigation/navbar.js
  web/src/components/navigation/navbarmobile.js
  web/src/components/navigation/navbarpc.js
Labels: enhancement
